apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newslens-api
  namespace: newslens
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: newslens-api
                port:
                  number: 80
