apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: newslens-api
  namespace: newslens
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: newslens-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8000

