apiVersion: v1
kind: Service
metadata:
  name: newslens-api
  namespace: newslens
spec:
  selector:
    app.kubernetes.io/name: newslens-api
  ports:
    - name: http
      port: 80
      targetPort: http

